"""empty message

Revision ID: 41fc9fb34578
Revises: f90d2f4c6851
Create Date: 2021-05-06 02:12:58.088229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41fc9fb34578'
down_revision = 'f90d2f4c6851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumenes_investigacion', sa.Column('corpus_lemas_autores', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumenes_investigacion', 'corpus_lemas_autores')
    # ### end Alembic commands ###
