"""empty message

Revision ID: 7025664993c6
Revises: c5d68b11e0bd
Create Date: 2021-04-06 00:46:04.797818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7025664993c6'
down_revision = 'c5d68b11e0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diccionario_lema',
    sa.Column('lema', sa.String(length=500), nullable=False),
    sa.Column('palabras', sa.ARRAY(sa.String(length=500)), nullable=True),
    sa.PrimaryKeyConstraint('lema')
    )
    op.create_table('resumenes_investigacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_investigacion', sa.String(length=8), nullable=True),
    sa.Column('titulo_investigacion', sa.String(length=10000), nullable=True),
    sa.Column('resumen_investigacion', sa.Text(), nullable=True),
    sa.Column('estado_investigacion', sa.String(length=100), nullable=True),
    sa.Column('palabra_clave1', sa.String(length=500), nullable=True),
    sa.Column('palabra_clave2', sa.String(length=500), nullable=True),
    sa.Column('palabra_clave3', sa.String(length=500), nullable=True),
    sa.Column('palabra_clave4', sa.String(length=500), nullable=True),
    sa.Column('palabra_clave5', sa.String(length=500), nullable=True),
    sa.Column('convocatoria', sa.String(length=100), nullable=True),
    sa.Column('tipo_convocatoria', sa.String(length=100), nullable=True),
    sa.Column('anio_convocatoria', sa.Integer(), nullable=True),
    sa.Column('codigo_autor1', sa.Integer(), nullable=True),
    sa.Column('nombres_autor1', sa.String(length=100), nullable=True),
    sa.Column('apellidos_autor1', sa.String(length=100), nullable=True),
    sa.Column('programa_autor1', sa.String(length=500), nullable=True),
    sa.Column('facultad_autor1', sa.String(length=500), nullable=True),
    sa.Column('departamento_autor1', sa.String(length=500), nullable=True),
    sa.Column('grupo_investigacion1', sa.String(length=500), nullable=True),
    sa.Column('linea_investigacion1', sa.String(length=500), nullable=True),
    sa.Column('codigo_autor2', sa.Integer(), nullable=True),
    sa.Column('nombres_autor2', sa.String(length=100), nullable=True),
    sa.Column('apellidos_autor2', sa.String(length=100), nullable=True),
    sa.Column('programa_autor2', sa.String(length=500), nullable=True),
    sa.Column('facultad_autor2', sa.String(length=500), nullable=True),
    sa.Column('departamento_autor2', sa.String(length=500), nullable=True),
    sa.Column('grupo_investigacion2', sa.String(length=500), nullable=True),
    sa.Column('linea_investigacion2', sa.String(length=500), nullable=True),
    sa.Column('codigo_autor3', sa.Integer(), nullable=True),
    sa.Column('nombres_autor3', sa.String(length=100), nullable=True),
    sa.Column('apellidos_autor3', sa.String(length=100), nullable=True),
    sa.Column('programa_autor3', sa.String(length=500), nullable=True),
    sa.Column('facultad_autor3', sa.String(length=500), nullable=True),
    sa.Column('departamento_autor3', sa.String(length=500), nullable=True),
    sa.Column('grupo_investigacion3', sa.String(length=500), nullable=True),
    sa.Column('linea_investigacion3', sa.String(length=500), nullable=True),
    sa.Column('codigo_autor4', sa.Integer(), nullable=True),
    sa.Column('nombres_autor4', sa.String(length=100), nullable=True),
    sa.Column('apellidos_autor4', sa.String(length=100), nullable=True),
    sa.Column('programa_autor4', sa.String(length=500), nullable=True),
    sa.Column('facultad_autor4', sa.String(length=500), nullable=True),
    sa.Column('departamento_autor4', sa.String(length=500), nullable=True),
    sa.Column('grupo_investigacion4', sa.String(length=500), nullable=True),
    sa.Column('linea_investigacion4', sa.String(length=500), nullable=True),
    sa.Column('asesor1', sa.String(length=100), nullable=True),
    sa.Column('asesor2', sa.String(length=100), nullable=True),
    sa.Column('asesor3', sa.String(length=100), nullable=True),
    sa.Column('asesor4', sa.String(length=100), nullable=True),
    sa.Column('tipo_resumen', sa.String(length=20), nullable=True),
    sa.Column('corpus', sa.Text(), nullable=True),
    sa.Column('corpus_palabras', sa.Text(), nullable=True),
    sa.Column('corpus_lemas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resumenes_investigacion')
    op.drop_table('diccionario_lema')
    # ### end Alembic commands ###
