"""empty message

Revision ID: c5d68b11e0bd
Revises: 8556a31d92fb
Create Date: 2021-04-06 00:44:37.111953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d68b11e0bd'
down_revision = '8556a31d92fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diccionario_lema')
    op.drop_table('resumenes_investigacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resumenes_investigacion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_investigacion', sa.VARCHAR(length=8), autoincrement=False, nullable=True),
    sa.Column('titulo_investigacion', sa.VARCHAR(length=10000), autoincrement=False, nullable=True),
    sa.Column('resumen_investigacion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estado_investigacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('palabra_clave1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('palabra_clave2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('palabra_clave3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('palabra_clave4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('palabra_clave5', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('convocatoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tipo_convocatoria', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('anio_convocatoria', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('codigo_autor1', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombres_autor1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellidos_autor1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('programa_autor1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facultad_autor1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('departamento_autor1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('grupo_investigacion1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linea_investigacion1', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('codigo_autor2', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombres_autor2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellidos_autor2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('programa_autor2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facultad_autor2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('departamento_autor2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('grupo_investigacion2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linea_investigacion2', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('codigo_autor3', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombres_autor3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellidos_autor3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('programa_autor3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facultad_autor3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('departamento_autor3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('grupo_investigacion3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linea_investigacion3', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('codigo_autor4', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nombres_autor4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('apellidos_autor4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('programa_autor4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('facultad_autor4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('departamento_autor4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('grupo_investigacion4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('linea_investigacion4', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('asesor1', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('asesor2', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('asesor3', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('asesor4', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('tipo_resumen', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('corpus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('corpus_palabras', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('corpus_lemas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='resumenes_investigacion_pkey')
    )
    op.create_table('diccionario_lema',
    sa.Column('lema', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('palabras', postgresql.ARRAY(sa.VARCHAR(length=500)), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('lema', name='diccionario_lema_pkey')
    )
    # ### end Alembic commands ###
